method1:
		g++ 3_sub_m_1.cpp -o 1_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method2:
		g++ 3_sub_m_2.cpp -o 2_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method3:
		g++ 3_sub_m_3.cpp -o 3_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method4:
		g++ 3_sub_m_4.cpp -o 4_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method5:
		g++ 3_sub_m_5.cpp -o 5_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method6:
		g++ 3_sub_m_6.cpp -o 6_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
method7:
		g++ 3_sub_m_7.cpp -o 7_method -pthread -std=c++11 `pkg-config --cflags --libs opencv4`
clean1:
		rm ./1_method
		rm out_method1.csv
clean2:
		rm ./2_method
		rm method2.txt
clean3:
		rm ./3_method
clean4:
		rm ./4_method
		rm out_method_4.txt
clean5:
		rm ./5_method
clean6:
		rm ./6_method
clean7:
		rm ./7_method